update plugin install bin

diff --git a/jenkins-docker/Dockerfile b/jenkins-docker/Dockerfile
--- a/jenkins-docker/Dockerfile
+++ b/jenkins-docker/Dockerfile
@@ -36,6 +36,6 @@ RUN rm /opt/apache-maven-3.6.3-bin.tar.gz
 
 RUN apt-get install jq -y
 
-RUN `/usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt` || echo "Some errors occurred during plugin installation."
+RUN /bin/jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt || echo "Some errors occurred during plugin installation."
 
 RUN wget https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip && unzip terraform_0.12.16_linux_amd64.zip && mv terraform /usr/local/bin/
