Should do that stuff as entrypoints removing

diff --git a/jenkins-docker/Dockerfile b/jenkins-docker/Dockerfile
--- a/jenkins-docker/Dockerfile
+++ b/jenkins-docker/Dockerfile
@@ -53,25 +53,14 @@ fi
 ##### Configuration for jenkins ###########
 USER $JENKINS_USERNAME
 # Check if PLUGINS_FILE is provided and copy it, then run jenkins-plugin-cli
-RUN set -e; \
-if [ -n "$PLUGINS_FILE" ]; then \
-    COPY $PLUGINS_FILE /usr/share/jenkins/ref/plugins.txt && \
-    /bin/jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt || echo "Some errors occurred during plugin installation."; \
-fi
+COPY $PLUGINS_FILE /usr/share/jenkins/ref/plugins.txt 
+
+RUN /bin/jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt || echo "Some errors occurred during plugin installation."
 
 COPY $CONFIG_XML_FILE /var/jenkins_home/config.xml
 COPY $SCRIPT_APPROVAL_FILE /var/jenkins_home/scriptApproval.xml
 COPY $HUDSON_TASKS_FILE /var/jenkins_home/hudson.tasks.Maven.xml
 COPY $JENKINS_JOBS_DIR /var/jenkins_home/jobs
-
-
-# Check if either PKCS12_FILE or PKCS12_PASS is provided, and ensure both are provided if one is provided
 COPY $PKCS12_FILE /var/jenkins_home/$PKCS12_FILE; 
 
-RUN if [ -n "$PKCS12_FILE" ] || [ -n "$PKCS12_PASS" ]; then \
-    if [ -z "$PKCS12_FILE" ] || [ -z "$PKCS12_PASS" ]; then \
-        echo "Both PKCS12_FILE and PKCS12_PASS must be provided if either one is provided."; \
-        exit 1; \
-    fi; \
-    JENKINS_OPTS="$JENKINS_OPTS --httpsKeyStore=/var/jenkins_home/$PKCS12_FILE --httpsKeyStorePassword=$PKCS12_PASS"; \
-fi
+ENV JENKINS_OPTS="--httpPort=$JENKINS_HTTP_PORT --httpsPort=$JENKINS_HTTPS_PORT -Djenkins.install.runSetupWizard=$RUN_SETUP_WIZARD --httpsKeyStore=/var/jenkins_home/$PKCS12_FILE --httpsKeyStorePassword=$PKCS12_PASS"
