removing plugins that are not working with cli

diff --git a/jenkins-docker/Dockerfile_nonFisma b/jenkins-docker/Dockerfile_nonFisma
--- a/jenkins-docker/Dockerfile_nonFisma
+++ b/jenkins-docker/Dockerfile_nonFisma
@@ -1,4 +1,4 @@
-FROM jenkins/jenkins:2.385
+FROM jenkins/jenkins:2.38
 
 ARG S3_BUCKET
 
@@ -42,6 +42,7 @@ RUN rm /opt/apache-maven-3.6.3-bin.tar.gz
 
 RUN apt-get install jq -y
 
-RUN `/usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt` || echo "Some errors occurred during plugin installation."
+#RUN `/usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt` || echo "Some errors occurred during plugin installation."
+RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
 
 RUN wget https://releases.hashicorp.com/terraform/0.12.31/terraform_0.12.31_linux_amd64.zip && unzip terraform_0.12.31_linux_amd64.zip && mv terraform /usr/local/bin/
