[ALS-5279] - Adding Role Strategy Plugin (#89)
* # Disable plugin.  Making dockerfile more configurable.
* added configuration to disable setup wizard
* added configurations to make args optional in order to make container more portable.

* Swap user around

* moving debian sources

* some bash cleanup

* trying this way

* Should do that stuff as entrypoints removing

* adding cleanup and some ideas

* adding role-strategy plugin

* removing auto skip setup wizard.

* Syncing jobs from auth-dev

---------

Co-authored-by: Tom <Tom@dbmitdesainsmbp.private.wireless.med.harvard.edu>

diff --git a/jenkins-docker/Dockerfile b/jenkins-docker/Dockerfile
--- a/jenkins-docker/Dockerfile
+++ b/jenkins-docker/Dockerfile
@@ -1,4 +1,6 @@
 FROM jenkins/jenkins:lts
+# user to swap easily between OS operations and jenkins configuration.
+ENV JENKINS_USERNAME=$USER
 
 ARG JENKINS_DOCKER_TERRAFORM_DISTRO
 ARG PLUGINS_FILE
@@ -8,49 +10,58 @@ ARG HUDSON_TASKS_FILE
 ARG JENKINS_JOBS_DIR
 ARG PKCS12_FILE
 ARG PKCS12_PASS
+ARG JENKINS_HTTP_PORT=-1
+ARG JENKINS_HTTPS_PORT=8443
 
-COPY $PLUGINS_FILE /usr/share/jenkins/ref/plugins.txt
-
-COPY $CONFIG_XML_FILE /var/jenkins_home/config.xml
-
-COPY $SCRIPT_APPROVAL_FILE /var/jenkins_home/scriptApproval.xml
-
-COPY $HUDSON_TASKS_FILE /var/jenkins_home/hudson.tasks.Maven.xml
-
-COPY $JENKINS_JOBS_DIR /var/jenkins_home/jobs
-
-COPY $PKCS12_FILE /var/jenkins_home/jenkins.p12
-
-ENV JENKINS_OPTS="--httpPort=-1 --httpsPort=8443 --httpsKeyStore=/var/jenkins_home/jenkins.p12 --httpsKeyStorePassword=$PKCS12_PASS"
-
+# Can use this to swap users back to jenkins user without hardcoding it.  Safe to hardcode swap to root user.
+###### OS configs and package installations ########
+# We could run these commands and build an image then configure jenkins only in this dockerfile instead of directly using the jenkins stock image
 USER root
 
+# debian repos to install openjdk headless? 
+# Jenkins must have a better way to manage JRE ....
 RUN echo deb http://archive.debian.org/debian stretch-backports main >> /etc/apt/sources.list
-
 RUN echo deb http://archive.debian.org/debian stretch main >> /etc/apt/sources.list
 
 RUN apt-get update
 
-RUN apt-get -y install apt-transport-https
-
-RUN apt-get -y install python3-pip
-
-RUN apt-get -y install wget
-
-RUN pip3 install --no-input awscli --upgrade --break-system-packages
-
-RUN curl -fsSL https://get.docker.com | sh
-
-RUN docker --version
-
 RUN apt-get -y -t stretch-backports install openjdk-11-jdk-headless
 
-RUN apt-get -y install maven
+RUN apt-get -y install apt-transport-https \
+    python3-pip \
+    wget
 
+# maybe not the best way to install awscli 
+# see https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
+RUN pip3 install --no-input awscli --upgrade --break-system-packages
+
+RUN set -e; \
+    curl -fsSL https://get.docker.com | sh && \
+    docker --version
+
+# maven
+RUN apt-get -y install maven
+# jq
 RUN apt-get install jq -y
+# terraform
+RUN wget -c $JENKINS_DOCKER_TERRAFORM_DISTRO -O /opt/terraform.zip && \
+    unzip /opt/terraform.zip -d /usr/local/bin/ && rm -f /opt/terraform.zip
+
+# Cleanup
+RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/*
+
+##### Configuration for jenkins ###########
+USER $JENKINS_USERNAME
+# Check if PLUGINS_FILE is provided and copy it, then run jenkins-plugin-cli
+COPY $PLUGINS_FILE /usr/share/jenkins/ref/plugins.txt 
 
 RUN /bin/jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt || echo "Some errors occurred during plugin installation."
 
-RUN wget -c $JENKINS_DOCKER_TERRAFORM_DISTRO -O /opt/terraform.zip 
+COPY $CONFIG_XML_FILE /var/jenkins_home/config.xml
+COPY $SCRIPT_APPROVAL_FILE /var/jenkins_home/scriptApproval.xml
+COPY $HUDSON_TASKS_FILE /var/jenkins_home/hudson.tasks.Maven.xml
+COPY $JENKINS_JOBS_DIR /var/jenkins_home/jobs
+COPY $PKCS12_FILE /var/jenkins_home/$PKCS12_FILE
 
-RUN unzip /opt/terraform.zip -d /usr/local/bin/
+# Should set env var at runtime using an entrypoint.
+ENV JENKINS_OPTS="--httpPort=$JENKINS_HTTP_PORT --httpsPort=$JENKINS_HTTPS_PORT --httpsKeyStore=/var/jenkins_home/$PKCS12_FILE --httpsKeyStorePassword=$PKCS12_PASS"
